---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Tartalom
- type: directory
  path: cms/cikkek
  label: Cikkek
  create: all
  match: "**/*"
  templates:
  - cikk-withbigcontentarea-template
- type: heading
  label: Oldalak
- type: document
  path: cms/oldalak
  label: Fooldal
  match: "**/*"
upload_dir: public/uploads
public_path: "/public/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
